### ISSUE TITLE
Modify example or fixtures for testing to use dynamic projects and networks

### ISSUE THREAD

**Issue by ingwarr** [terraform-google-modules/terraform-google-vpn#15] opened 2019-07-25 14:10 UTC
Fix this: https://github.com/terraform-google-modules/terraform-google-vpn/pull/12#issuecomment-513921158

And update the testing to the new approach as documented [here](https://docs.google.com/document/d/1eiHpZlhEDMDG8gi4LHyv2aZs1TJmeFlF8sqCE57_j4A/edit#heading=h.rz8l5qn0ygc0).

**Comment by aaron-lane** [comment] 2019-09-27 19:12
Duplicate of #20 .

**Closed by aaron-lane** 2019-09-27 19:12 UTC
Labels: enhancement
